export const SET_INITIALIZED = 'SET_INITIALIZED';
export const SET_INTERVAL = 'SET_INTERVAL';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_COINS = 'SET_COINS';
export const TOGGLE_COIN_SELECTION = 'TOGGLE_COIN_SELECTION';
